# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Health Data Project Toolkit
tagline:             'a Guide for CA Health Data Ambassadors'
description:         'A statewide pilot project funded by the <a href="http://www.chcf.org/" target="_blank">California HealthCare Foundation’s</a> <a href="http://www.chcf.org/projects/2012/free-the-data" target="_blank">Free the Data</a> Initiative'
url:                 http://toolkit.cahealthdata.org
baseurl:             'http://patrick95350.github.io/opendata2'
paginate:            5

# About/contact
author:
  name:              California Health Data Project
  url:               https://twitter.com/@CAHealthData
  email:             health@codeforsacramento.org

# Custom vars
version:             1.0
github:
  repo:           https://github.com/CAHealthData/toolkit
